USE [master]
GO
/****** Object:  Database [STGenetics2]    Script Date: 23/04/2024 7:15:22 p. m. ******/
CREATE DATABASE [STGenetics2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STGenetics2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\STGenetics2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STGenetics2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\STGenetics2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [STGenetics2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STGenetics2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [STGenetics2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [STGenetics2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [STGenetics2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [STGenetics2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [STGenetics2] SET ARITHABORT OFF 
GO
ALTER DATABASE [STGenetics2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [STGenetics2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [STGenetics2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [STGenetics2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [STGenetics2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [STGenetics2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [STGenetics2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [STGenetics2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [STGenetics2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [STGenetics2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [STGenetics2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [STGenetics2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [STGenetics2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [STGenetics2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [STGenetics2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [STGenetics2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [STGenetics2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [STGenetics2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [STGenetics2] SET  MULTI_USER 
GO
ALTER DATABASE [STGenetics2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [STGenetics2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [STGenetics2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [STGenetics2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [STGenetics2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [STGenetics2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [STGenetics2] SET QUERY_STORE = ON
GO
ALTER DATABASE [STGenetics2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [STGenetics2]
GO
/****** Object:  Table [dbo].[Food]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Food](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Price] [float] NULL,
	[FoodTypeId] [int] NULL,
 CONSTRAINT [PK_Element] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FoodType]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FoodType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_ElementType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NULL,
	[FoodId] [int] NULL,
 CONSTRAINT [PK_OrderItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TotalPrice] [float] NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Food]  WITH CHECK ADD  CONSTRAINT [FK_Element_Element] FOREIGN KEY([FoodTypeId])
REFERENCES [dbo].[FoodType] ([Id])
GO
ALTER TABLE [dbo].[Food] CHECK CONSTRAINT [FK_Element_Element]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Food] FOREIGN KEY([FoodId])
REFERENCES [dbo].[Food] ([Id])
GO
ALTER TABLE [dbo].[OrderItems] CHECK CONSTRAINT [FK_OrderItems_Food]
GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Orders1] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Orders] ([Id])
GO
ALTER TABLE [dbo].[OrderItems] CHECK CONSTRAINT [FK_OrderItems_Orders1]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Order_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Order_User]
GO
/****** Object:  StoredProcedure [dbo].[SP_CreateOrder]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CreateOrder] 
(@TotalPrice FLOAT, 
@UserId INT,
@retID int OUTPUT) 
AS 
BEGIN 
	INSERT INTO Orders (TotalPrice, UserId) VALUES (@TotalPrice, @UserId)
	SELECT @retID = SCOPE_IDENTITY()
END
GO
/****** Object:  StoredProcedure [dbo].[SP_CreateUser]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CreateUser] 
(@Name VARCHAR(50), 
@retID int OUTPUT) 
AS 
BEGIN 
	INSERT INTO Users (Name) VALUES (@Name)
	SELECT @retID = SCOPE_IDENTITY()
END
GO
/****** Object:  StoredProcedure [dbo].[SP_InsertUser]    Script Date: 23/04/2024 7:15:22 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_InsertUser] 
(@Name VARCHAR(50), 
@retID int OUTPUT) 
AS 
BEGIN 
	INSERT INTO Users (Name) VALUES (@Name)
	SELECT @retID = SCOPE_IDENTITY()
END
GO
USE [master]
GO
ALTER DATABASE [STGenetics2] SET  READ_WRITE 
GO

INSERT INTO FoodType VALUES ('Sandwich')
INSERT INTO FoodType VALUES ('Extra')

INSERT INTO Food VALUES ('Burger', 5, 1)
INSERT INTO Food VALUES ('Egg', 4.5, 1)
INSERT INTO Food VALUES ('Bacon', 7, 1)
INSERT INTO Food VALUES ('Fries', 2, 2)
INSERT INTO Food VALUES ('Soft drink', 2.5, 2)

INSERT INTO Users VALUES ('admin')